//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Status string

const (
	Status_NotStarted Status = "NotStarted"
	Status_InProgress Status = "InProgress"
	Status_Completed  Status = "Completed"
)

var StatusAllValues = []Status{
	Status_NotStarted,
	Status_InProgress,
	Status_Completed,
}

func (e *Status) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "NotStarted":
		*e = Status_NotStarted
	case "InProgress":
		*e = Status_InProgress
	case "Completed":
		*e = Status_Completed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Status enum")
	}

	return nil
}

func (e Status) String() string {
	return string(e)
}
