syntax = "proto3";

package task.v1;

import "google/protobuf/timestamp.proto";

enum Status {
  STATUS_UNSPECIFIED = 0;
  STATUS_NOT_STARTED = 1;
	STATUS_IN_PROGRESS = 2;
	STATUS_COMPLETED = 3;
}

message Task {
  string id = 1;
  string title = 2;
  optional string description = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp last_updated_at = 5;
  bool deleted = 6;
  Status status = 7;
}

message CreateTaskRequest {
  string title = 1;
  optional string description = 2;
}

message CreateTaskResponse {
  Task task = 1;
}

message GetTaskRequest {
  string id = 1;
}

message GetTaskResponse {
  Task task = 1;
}

message UpdateTaskRequest {
  string id = 1;
  string title = 2;
  optional string description = 3;
  optional Status status = 4;
}

message UpdateTaskResponse {
  Task task = 1;
}

message DeleteTaskRequest {
  string id = 1;
}

message DeleteTaskResponse {
  bool success = 1;
}

service TaskService {
  rpc CreateTask(CreateTaskRequest) returns (CreateTaskResponse);
  rpc GetTask(GetTaskRequest) returns (GetTaskResponse);
  rpc UpdateTask(UpdateTaskRequest) returns (UpdateTaskResponse);
  rpc DeleteTask(DeleteTaskRequest) returns (DeleteTaskResponse);
}
