//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Task = newTaskTable("public", "task", "")

type taskTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz
	Description   postgres.ColumnString
	Title         postgres.ColumnString
	LastUpdatedAt postgres.ColumnTimestampz
	Deleted       postgres.ColumnBool
	Status        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TaskTable struct {
	taskTable

	EXCLUDED taskTable
}

// AS creates new TaskTable with assigned alias
func (a TaskTable) AS(alias string) *TaskTable {
	return newTaskTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TaskTable with assigned schema name
func (a TaskTable) FromSchema(schemaName string) *TaskTable {
	return newTaskTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TaskTable with assigned table prefix
func (a TaskTable) WithPrefix(prefix string) *TaskTable {
	return newTaskTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TaskTable with assigned table suffix
func (a TaskTable) WithSuffix(suffix string) *TaskTable {
	return newTaskTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTaskTable(schemaName, tableName, alias string) *TaskTable {
	return &TaskTable{
		taskTable: newTaskTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newTaskTableImpl("", "excluded", ""),
	}
}

func newTaskTableImpl(schemaName, tableName, alias string) taskTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		DescriptionColumn   = postgres.StringColumn("description")
		TitleColumn         = postgres.StringColumn("title")
		LastUpdatedAtColumn = postgres.TimestampzColumn("last_updated_at")
		DeletedColumn       = postgres.BoolColumn("deleted")
		StatusColumn        = postgres.StringColumn("status")
		allColumns          = postgres.ColumnList{IDColumn, CreatedAtColumn, DescriptionColumn, TitleColumn, LastUpdatedAtColumn, DeletedColumn, StatusColumn}
		mutableColumns      = postgres.ColumnList{CreatedAtColumn, DescriptionColumn, TitleColumn, LastUpdatedAtColumn, DeletedColumn, StatusColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn, LastUpdatedAtColumn, DeletedColumn, StatusColumn}
	)

	return taskTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		CreatedAt:     CreatedAtColumn,
		Description:   DescriptionColumn,
		Title:         TitleColumn,
		LastUpdatedAt: LastUpdatedAtColumn,
		Deleted:       DeletedColumn,
		Status:        StatusColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
