//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Status = &struct {
	NotStarted postgres.StringExpression
	InProgress postgres.StringExpression
	Completed  postgres.StringExpression
}{
	NotStarted: postgres.NewEnumValue("NotStarted"),
	InProgress: postgres.NewEnumValue("InProgress"),
	Completed:  postgres.NewEnumValue("Completed"),
}
