name: Build and Deploy to GCP
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    environment: prod
    defaults:
      run:
        working-directory: ./server
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          create_credentials_file: true
          workload_identity_provider: "${{ vars.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ vars.SERVICE_ACCOUNT_EMAIL }}"
          project_id: "${{ vars.GCP_PROJECT_ID }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Login to GCP
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}
      - name: Authenticate Docker with GHCR
        run: |-
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Authenticate Docker with GCR
        run: |-
          gcloud auth print-access-token --impersonate-service-account ${{ vars.SERVICE_ACCOUNT_EMAIL }} | docker login -u oauth2accesstoken --password-stdin gcr.io
      - name: Build Docker image
        run: |
          docker buildx build \
            --build-arg GCP_PROJECT_ID="${{ vars.GCP_PROJECT_ID }}" \
            -t ghcr.io/jansdhillon/${{ vars.SERVICE_NAME }}:latest \
            .
      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/jansdhillon/${{ vars.SERVICE_NAME }}:latest
      - name: Push to GCR
        run: |
          docker tag ghcr.io/jansdhillon/${{ vars.SERVICE_NAME }}:latest gcr.io/${{ vars.ARTIFACT_REPO }}
          docker push gcr.io/${{ vars.ARTIFACT_REPO }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
            --image gcr.io/${{ vars.ARTIFACT_REPO }} \
            --region ${{ vars.REGION }} \
            --project ${{ vars.GCP_PROJECT_ID }} \
            --platform managed \
            --allow-unauthenticated
